packages:
  - 'packages/*'
  - "apps/api"
  - "apps/mobile"
  - "apps/web"
  - "apps/scrapper"
  - "apps/whatsapp"
  - "apps/scheduler"
syncInjectedDepsAfterScripts:
- build
injectWorkspacePackages: true