export type ChatwootInbox = {
    id: number;
    avatar_url: string;
    channel_id: number;
    name: string;
    channel_type: string;
    greeting_enabled: boolean;
    greeting_message: string | null;
    working_hours_enabled: boolean;
    enable_email_collect: boolean;
    csat_survey_enabled: boolean;
    enable_auto_assignment: boolean;
    auto_assignment_config: unknown;
    out_of_office_message: string | null;
    working_hours: WorkingHour[];
    timezone: string;
    callback_webhook_url: string | null;
    allow_messages_after_resolved: boolean;
    lock_to_single_conversation: boolean;
    sender_name_type: string;
    business_name: string | null;
    widget_color: string | null;
    website_url: string | null;
    hmac_mandatory: boolean;
    welcome_title: string | null;
    welcome_tagline: string | null;
    web_widget_script: string | null;
    website_token: string | null;
    selected_feature_flags: string | null;
    reply_time: string | null;
    messaging_service_sid: string | null;
    phone_number: string | null;
    webhook_url: string;
    inbox_identifier: string;
    additional_attributes: InboxAdditionalAttributes | null;
    provider: string | null;
};
export type WorkingHour = {
    day_of_week: number;
    closed_all_day: boolean;
    open_hour: Number;
    open_minutes: Number;
    close_hour: Number;
    close_minutes: Number;
    open_all_day: boolean;
};

export type InboxAdditionalAttributes = Partial<{
    isWhatsappAdapter?: boolean;
    assistant_id?: string;
    shouldRespond?: boolean;
}>;
