import { z } from "@hono/zod-openapi"
import { ManyItemsResponse } from "./index.js"

export type FindPolizasResponse = ManyItemsResponse<z.infer<typeof searchPolizaResponseSchema>>


export const searchPolizaResponseSchema = z.object({
    id: z.number(),
    company: z.string().nullable().optional(),
    account: z.string(),
    numeroPoliza: z.string().nullable().optional(),
    asegurado: z.string().nullable().optional(),
    agente: z.string().nullable().optional(),
    conducto: z.string().nullable().optional(),
    serie: z.string().nullable().optional(),
    vehiculoId: z.number().nullable().optional(),
    vehiculo: z.string().nullable().optional(),
    vigenciaInicio: z.string().nullable().optional(),
    vigenciaFin: z.string().nullable().optional(),
    primaTotal: z.string().nullable().optional(),
    iva: z.string().nullable().optional(),
    origen: z.string().nullable().optional(),
    status: z.string().nullable().optional(),
})

export type GetOnePolizaResponse = z.infer<typeof getOnePolizaResponseSchema>
export const getOnePolizaResponseSchema = z.object({
    poliza: z.object({
        id: z.number(),
        numeroPoliza: z.string().nullable().optional(),
        vigenciaInicio: z.string().nullable().optional(),
        vigenciaFin: z.string().nullable().optional(),
        primaTotal: z.string().nullable().optional(),
        iva: z.string().nullable().optional(),
        origen: z.string().nullable().optional(),
        ramo: z.string().nullable().optional(),
        subramo: z.string().nullable().optional(),
        uso: z.string().nullable().optional(),
        servicio: z.string().nullable().optional(),
        modoPago: z.string().nullable().optional(),
        company: z.string().nullable().optional(),
        vehiculo: z.string().nullable().optional(),
        vehiculoDescripcion: z.string().nullable().optional(),
        vehiculoTipo: z.string().nullable().optional(),
        vehiculoCarroceria: z.string().nullable().optional(),
        vehiculoColor: z.string().nullable().optional(),
        vehiculoOcupantes: z.number().nullable().optional(),
        asegurado: z.string().nullable().optional(),
        aseguradoDireccion: z.string().nullable().optional(),
        aseguradoRfc: z.string().nullable().optional(),
        aseguradoCelular: z.string().nullable().optional(),
        motor: z.string().nullable().optional(),
        numeroSerie: z.string().nullable().optional(),
        numeroEconomico: z.string().nullable().optional(),
        polizaAnterior: z.string().nullable().optional(),
        polizaRenovada: z.string().nullable().optional(),
        cobertura: z.string().nullable().optional(),
        totalIncisos: z.number().nullable().optional(),
        incisosVigentes: z.number().nullable().optional(),
        incisosCancelados: z.number().nullable().optional(),
        inciso: z.string().nullable().optional(),
        endoso: z.string().nullable().optional(),
        oficinaEmision: z.string().nullable().optional(),
        porcentajeDescuento: z.string().nullable().optional(),
        fechaEmision: z.string().nullable().optional(),
        tarifa: z.string().nullable().optional(),
        modoPagoId: z.number().nullable().optional(),
        moneda: z.string().nullable().optional(),
        descripcionPago: z.string().nullable().optional(),
        periodoGracia: z.string().nullable().optional(),
        primaNeta: z.string().nullable().optional(),
        recargoFinacieroPorcentual: z.string().nullable().optional(),
        financiamiento: z.string().nullable().optional(),
        costoExpedicion: z.string().nullable().optional(),
        subtotal: z.string().nullable().optional(),
        total: z.string().nullable().optional(),
        coberturas: z.array(z.object({
            prima: z.string().nullable().optional(),
            cobertura: z.string().nullable().optional(),
            deducible: z.string().nullable().optional(),
            sumaAsegurada: z.string().nullable().optional(),
        })),
        polizaEstatus: z.string().nullable().optional(),
        created: z.string().nullable().optional(),
        lastSync: z.string().nullable().optional(),
        origenId: z.number().nullable().optional(),
        agente: z.string().nullable().optional(),
        conducto: z.string().nullable().optional(),
        saasId: z.string().nullable().optional(),
        esMaestra: z.boolean().nullable().optional(),
        ramoId: z.number().nullable().optional(),
        subRamoId: z.number().nullable().optional(),
        companyId: z.string().nullable().optional(),
        agenteId: z.number().nullable().optional(),
        conductoId: z.number().nullable().optional(),
        vehiculoId: z.number().nullable().optional(),
        asegurado_id: z.number().nullable().optional(),
        usoId: z.number().nullable().optional(),
        servicioId: z.number().nullable().optional(),
        placas: z.string().nullable().optional(),

    }),
    movimientos: z.array(z.object({
        created: z.string().nullable().optional(),
        motivo: z.string().nullable().optional(),
        tipoMovimiento: z.string().nullable().optional(),
        fechaMovimiento: z.string().nullable().optional(),
    })),
    siniestros: z.array(z.object({
        id: z.number(),
        saasId: z.string().nullable().optional(),
        polizaId: z.number().nullable().optional(),
        agenteId: z.number().nullable().optional(),
        conductoId: z.number().nullable().optional(),
        aseguradoId: z.number().nullable().optional(),
        vehiculoId: z.number().nullable().optional(),
        causaId: z.number().nullable().optional(),
        companyId: z.string().nullable().optional(),
        polizaPrimaneta: z.string().nullable().optional(),
        numeroSiniestro: z.string().nullable().optional(),
        montoEstimado: z.string().nullable().optional(),
        montoActualizado: z.string().nullable().optional(),
        montoFinal: z.string().nullable().optional(),
        fechaSiniestro: z.string().nullable().optional(),
        horaSiniestro: z.string().nullable().optional(),
        fechaReporte: z.string().nullable().optional(),
        horaReporte: z.string().nullable().optional(),
        fechaCierre: z.string().nullable().optional(),
        codigoPostal: z.string().nullable().optional(),
        created: z.string().nullable().optional(),
        updated: z.string().nullable().optional(),
        numeroReporte: z.string().nullable().optional(),
        enSeguimiento: z.boolean().nullable().optional(),
        causa: z.string().nullable().optional(),
        detalle: z.object({
            numeroReporte: z.string().nullable().optional(),
            fechaReporte: z.string().nullable().optional(),
            colonia: z.string().nullable().optional(),
            comentarios: z.string().nullable().optional(),
            causa: z.string().nullable().optional(),
            telefono: z.string().nullable().optional(),
            conductor: z.string().nullable().optional(),
            ubicacion: z.string().nullable().optional(),
            ajustador: z.object({
                nombre: z.string().nullable().optional(),
                llegada: z.string().nullable().optional(),
                termino: z.string().nullable().optional(),
            }),
            involucrados: z.array(z.object({
                conductor: z.string().nullable().optional(),
                tipo_involucrado: z.string().nullable().optional(),
                folio_asignacion: z.string().nullable().optional(),
                proveedor: z.string().nullable().optional(),
            })),

        }).nullable().optional(),
        actividades: z.array(z.object({
            tipoActividad: z.string().nullable().optional(),
            files: z.array(
                z.object({
                    url: z.string().nullable().optional(),
                    fileName: z.string().nullable().optional(),
                    mimeType: z.string().nullable().optional(),
                    path: z.number().nullable().optional(),
                    error: z.string().nullable().optional(),
                })
            ).nullable().optional(),
            comentario: z.string().nullable().optional(),
            user: z.string().nullable().optional(),
            timestamp: z.number().nullable().optional(),
        })).nullable().optional(),
    })),
    endosos: z.array(z.object({
        id: z.number(),
        numeroEndoso: z.string().nullable().optional(),
        fechaEmision: z.string().nullable().optional(),
        fechaVencimiento: z.string().nullable().optional(),
        prima: z.string().nullable().optional(),
        tipoEndoso: z.string().nullable().optional(),
        numeroRecibo: z.string().nullable().optional(),
        remesa: z.string().nullable().optional(),
        fechaPago: z.string().nullable().optional(),
        fechaRegistroPago: z.string().nullable().optional(),
        importe: z.string().nullable().optional(),
        estado: z.string().nullable().optional(),
    })),
    recibos: z.array(z.object({
        id: z.number(),
        saasId: z.string().nullable().optional(),
        polizaId: z.number().nullable().optional(),
        numeroRecibo: z.string().nullable().optional(),
        serie: z.string().nullable().optional(),
        folio: z.string().nullable().optional(),
        serieEmision: z.string().nullable().optional(),
        importe: z.string().nullable().optional(),
        primaNetaComision: z.string().nullable().optional(),
        vigenciaInicio: z.string().nullable().optional(),
        vigenciaFin: z.string().nullable().optional(),
        estado: z.string().nullable().optional(),
        created: z.string().nullable().optional(),
    })),
    remesas: z.array(z.object({
        id: z.number(),
        saasId: z.string().nullable().optional(),
        polizaId: z.number().nullable().optional(),
        reciboId: z.number().nullable().optional(),
        numeroRecibo: z.string().nullable().optional(),
        numeroPoliza: z.string().nullable().optional(),
        numeroEndoso: z.string().nullable().optional(),
        serie: z.string().nullable().optional(),
        remesa: z.string().nullable().optional(),
        clave: z.string().nullable().optional(),
        concepto: z.string().nullable().optional(),
        fechaPago: z.string().nullable().optional(),
        importe: z.string().nullable().optional(),
        comision: z.string().nullable().optional(),
        cargo: z.string().nullable().optional(),
        abono: z.string().nullable().optional(),
        contabilizado: z.string().nullable().optional(),
        porcentajeComision: z.string().nullable().optional(),
        comisionConducto: z.string().nullable().optional(),
        created: z.string().nullable().optional(),
    })),
    contactos: z.array(z.object({
        id: z.number(),
        saasId: z.string().nullable().optional(),
        agenteId: z.number().nullable().optional(),
        conductoId: z.number().nullable().optional(),
        nombre: z.string().nullable().optional(),
        email: z.string().nullable().optional(),
        rfc: z.string().nullable().optional(),
        telefono: z.string().nullable().optional(),
        direccion: z.string().nullable().optional(),
        ciudad: z.string().nullable().optional(),
        pais: z.string().nullable().optional(),
        fechaNacimiento: z.string().nullable().optional(),
        esCliente: z.boolean().nullable().optional(),
        fechaCreacion: z.string().nullable().optional(),
        fechaConversion: z.string().nullable().optional(),
        fechaActualizacion: z.string().nullable().optional(),
        created: z.string().nullable().optional(),
    }))
})




